#!/usr/bin/env python3
"""Guard against packaging/build tooling leaking into the runtime SBOM.

Fails if the CycloneDX SBOM lists any bootstrap/build/publish tooling
component (pip, setuptools, wheel, build, twine, cyclonedx-bom, ...). Such a
component appearing in a *runtime* SBOM means it was generated by scanning
the tooling environment used to build/check/scan the release (which has
`build`, `twine`, and `cyclonedx-bom` installed, along with pip's own
bootstrap dependencies) instead of a clean environment containing only the
already-built wheel and the runtime dependencies pip resolved for it.

Also fails if the SDK's own declared runtime dependencies are missing from
the SBOM: an SBOM that omits them is just as wrong as one that includes
build tooling, since it means the scanned environment did not actually have
the wheel's dependencies installed (e.g. the wrong directory was scanned).

Usage:
    python scripts/check_sbom.py sbom.cdx.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Packaging/build/publish tooling that must never appear as a component in
# a *runtime* SBOM. Presence of any of these is a strong signal that the
# tooling environment (not a clean runtime-only environment) was scanned.
BANNED_COMPONENTS = frozenset(
    {
        "pip",
        "setuptools",
        "wheel",
        "build",
        "twine",
        "cyclonedx-bom",
        "cyclonedx-python-lib",
    }
)

# Runtime dependencies streamline-sdk actually declares in pyproject.toml's
# [project].dependencies. An SBOM for the shipped wheel must list these, or
# the scanned environment did not have the wheel's dependencies installed.
REQUIRED_COMPONENTS = frozenset({"aiokafka", "cryptography"})


def _component_names(sbom: dict) -> set[str]:
    names = set()
    for component in sbom.get("components", []):
        name = component.get("name")
        if name:
            names.add(str(name).lower())
    return names


def check_sbom(sbom_path: Path) -> list[str]:
    """Return human-readable problems found in the SBOM at ``sbom_path``.

    An empty list means the SBOM passed all checks.
    """
    sbom = json.loads(sbom_path.read_text(encoding="utf-8"))
    names = _component_names(sbom)

    problems = []

    forbidden_found = sorted(names & BANNED_COMPONENTS)
    if forbidden_found:
        problems.append(
            "SBOM contains packaging/build tooling components that must "
            f"never appear in a runtime SBOM: {forbidden_found}. This "
            "means the SBOM was generated by scanning the build/release "
            "tooling environment (with build/twine/cyclonedx-bom "
            "installed) instead of a clean runtime-only environment "
            "containing just the built wheel and its dependencies."
        )

    missing_required = sorted(REQUIRED_COMPONENTS - names)
    if missing_required:
        problems.append(
            f"SBOM is missing required runtime dependencies: {missing_required}. "
            "This means the scanned environment did not actually have the "
            "wheel's runtime dependencies installed."
        )

    return problems


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(f"usage: {argv[0]} <sbom.cdx.json>", file=sys.stderr)
        return 2

    sbom_path = Path(argv[1])
    if not sbom_path.is_file():
        print(f"SBOM check failed: {sbom_path} does not exist", file=sys.stderr)
        return 1

    problems = check_sbom(sbom_path)
    if problems:
        for problem in problems:
            print(f"SBOM check failed: {problem}", file=sys.stderr)
        return 1

    print(f"SBOM check passed: {sbom_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
